  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - native-vs-snapstart-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    NativeVsSnapstart:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: native-vs-snapstart-jar
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: ../target/function.zip
        AutoPublishAlias: live
        MemorySize: 1024
        Policies:
          - AWSLambdaBasicExecutionRole
          - AmazonDynamoDBFullAccess
        Timeout: 15
        Events:
          HttpApiEvent:
            Type: HttpApi

  Outputs:
    NativeVsJarApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: NativeVsJarApi
